package com.example.myfoodapp.activities.admin.db;

//import necessary classes for Room database annotations
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

//@Entity annotation indicates that this class represents an entity in the Room database
@Entity
public class Category {

    //The @PrimaryKey annotation specifies that the uid field is the primary key for the entity
    //the primary key value will be automatically generated by the Room database when inserting new records (autoGenerate parameter is set to true)
    @PrimaryKey(autoGenerate = true)
    public int uid;

    //The @ColumnInfo annotation allows you to specify details about a column in the entity table.
    @ColumnInfo(name = "categoryName")
    public String categoryName;

}