package com.example.myfoodapp.activities.admin.db;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

//this class represents an entity in the Room database
@Entity
public class Items {   // Each instance of this class will be stored as a row in the corresponding table.

    //The @PrimaryKey annotation marks the uid field as the primary key
    //The autoGenerate attribute specifies that the primary key values will be automatically generated by Room.
    @PrimaryKey(autoGenerate = true)
    public int uid;

    //specify additional details about a column
    @ColumnInfo(name = "itemName")
    //indicates column name
    public  String itemName;

    @ColumnInfo(name = "categoryId")
    public  int categoryId;

    @ColumnInfo(name = "completed")
    public  boolean completed;
}